In [2]:
import tensorflow as tf

In [3]:
from tensorflow import keras

In [4]:
from tensorflow.keras import layers,Sequential

In [5]:
import matplotlib.pyplot as plt

In [6]:
import os

In [7]:
from PIL import Image

In [8]:
import numpy as np

In [9]:
import cv2

In [10]:
image_directory = "C:/Users/admin/Desktop/cimage"

In [11]:
image_directory

'C:/Users/admin/Desktop/cimage'

In [12]:
parasitized_images= os.listdir(image_directory + "/parasitized/")

In [13]:
parasitized_images

['C33P1thinF_IMG_20150619_114756a_cell_179.png',
 'C33P1thinF_IMG_20150619_114756a_cell_180.png',
 'C33P1thinF_IMG_20150619_114756a_cell_181.png',
 'C33P1thinF_IMG_20150619_114756a_cell_182.png',
 'C33P1thinF_IMG_20150619_115740a_cell_161.png',
 'C33P1thinF_IMG_20150619_115740a_cell_162.png',
 'C33P1thinF_IMG_20150619_115740a_cell_163.png',
 'C33P1thinF_IMG_20150619_115808a_cell_205.png',
 'C33P1thinF_IMG_20150619_115808a_cell_206.png',
 'C33P1thinF_IMG_20150619_120645a_cell_215.png',
 'C33P1thinF_IMG_20150619_120645a_cell_216.png',
 'C33P1thinF_IMG_20150619_120645a_cell_217.png',
 'C33P1thinF_IMG_20150619_120742a_cell_210.png',
 'C33P1thinF_IMG_20150619_120804a_cell_224.png',
 'C33P1thinF_IMG_20150619_120838a_cell_222.png',
 'C33P1thinF_IMG_20150619_121102a_cell_193.png',
 'C33P1thinF_IMG_20150619_121229a_cell_177.png',
 'C33P1thinF_IMG_20150619_121229a_cell_178.png',
 'C33P1thinF_IMG_20150619_121229a_cell_179.png',
 'C33P1thinF_IMG_20150619_121300a_cell_156.png',
 'C33P1thinF_IMG_201

In [14]:
for i in enumerate(parasitized_images):
    print(i)

(0, 'C33P1thinF_IMG_20150619_114756a_cell_179.png')
(1, 'C33P1thinF_IMG_20150619_114756a_cell_180.png')
(2, 'C33P1thinF_IMG_20150619_114756a_cell_181.png')
(3, 'C33P1thinF_IMG_20150619_114756a_cell_182.png')
(4, 'C33P1thinF_IMG_20150619_115740a_cell_161.png')
(5, 'C33P1thinF_IMG_20150619_115740a_cell_162.png')
(6, 'C33P1thinF_IMG_20150619_115740a_cell_163.png')
(7, 'C33P1thinF_IMG_20150619_115808a_cell_205.png')
(8, 'C33P1thinF_IMG_20150619_115808a_cell_206.png')
(9, 'C33P1thinF_IMG_20150619_120645a_cell_215.png')
(10, 'C33P1thinF_IMG_20150619_120645a_cell_216.png')
(11, 'C33P1thinF_IMG_20150619_120645a_cell_217.png')
(12, 'C33P1thinF_IMG_20150619_120742a_cell_210.png')
(13, 'C33P1thinF_IMG_20150619_120804a_cell_224.png')
(14, 'C33P1thinF_IMG_20150619_120838a_cell_222.png')
(15, 'C33P1thinF_IMG_20150619_121102a_cell_193.png')
(16, 'C33P1thinF_IMG_20150619_121229a_cell_177.png')
(17, 'C33P1thinF_IMG_20150619_121229a_cell_178.png')
(18, 'C33P1thinF_IMG_20150619_121229a_cell_179.png')
(19

In [15]:
for x, image_name in enumerate(parasitized_images):
    print(image_name)

C33P1thinF_IMG_20150619_114756a_cell_179.png
C33P1thinF_IMG_20150619_114756a_cell_180.png
C33P1thinF_IMG_20150619_114756a_cell_181.png
C33P1thinF_IMG_20150619_114756a_cell_182.png
C33P1thinF_IMG_20150619_115740a_cell_161.png
C33P1thinF_IMG_20150619_115740a_cell_162.png
C33P1thinF_IMG_20150619_115740a_cell_163.png
C33P1thinF_IMG_20150619_115808a_cell_205.png
C33P1thinF_IMG_20150619_115808a_cell_206.png
C33P1thinF_IMG_20150619_120645a_cell_215.png
C33P1thinF_IMG_20150619_120645a_cell_216.png
C33P1thinF_IMG_20150619_120645a_cell_217.png
C33P1thinF_IMG_20150619_120742a_cell_210.png
C33P1thinF_IMG_20150619_120804a_cell_224.png
C33P1thinF_IMG_20150619_120838a_cell_222.png
C33P1thinF_IMG_20150619_121102a_cell_193.png
C33P1thinF_IMG_20150619_121229a_cell_177.png
C33P1thinF_IMG_20150619_121229a_cell_178.png
C33P1thinF_IMG_20150619_121229a_cell_179.png
C33P1thinF_IMG_20150619_121300a_cell_156.png
C33P1thinF_IMG_20150619_121411a_cell_189.png
C33P1thinF_IMG_20150619_121411a_cell_190.png
C33P1thinF

In [16]:
dataset = []
label = []
size = 64

In [17]:
for x, image_name in enumerate(parasitized_images):
    if image_name.split(".")[1]=="png":
        image=cv2.imread(image_directory+"/parasitized/"+image_name)
        image = Image.fromarray(image,"RGB")
        image= image.resize((size,size))
        dataset.append(np.array(image))
        label.append(0)

In [18]:
len(dataset)

500

In [19]:
len(label)

500

In [20]:
dataset[0].size

12288

In [21]:
unparasitized_images = os.listdir(image_directory+"/unparasitized/")

unparasitized_images

In [22]:
unparasitized_images

['C12NThinF_IMG_20150614_124212_cell_111.png',
 'C12NThinF_IMG_20150614_124212_cell_120.png',
 'C12NThinF_IMG_20150614_124212_cell_125.png',
 'C12NThinF_IMG_20150614_124212_cell_138.png',
 'C12NThinF_IMG_20150614_124212_cell_161.png',
 'C12NThinF_IMG_20150614_124212_cell_165.png',
 'C12NThinF_IMG_20150614_124212_cell_187.png',
 'C12NThinF_IMG_20150614_124212_cell_200.png',
 'C12NThinF_IMG_20150614_124212_cell_213.png',
 'C12NThinF_IMG_20150614_124212_cell_224.png',
 'C12NThinF_IMG_20150614_124212_cell_70.png',
 'C12NThinF_IMG_20150614_124212_cell_71.png',
 'C12NThinF_IMG_20150614_124212_cell_73.png',
 'C12NThinF_IMG_20150614_124244_cell_21.png',
 'C12NThinF_IMG_20150614_124244_cell_45.png',
 'C12NThinF_IMG_20150614_124244_cell_47.png',
 'C12NThinF_IMG_20150614_124244_cell_50.png',
 'C12NThinF_IMG_20150614_124244_cell_64.png',
 'C12NThinF_IMG_20150614_124244_cell_90.png',
 'C1_thinF_IMG_20150604_104722_cell_115.png',
 'C1_thinF_IMG_20150604_104722_cell_123.png',
 'C1_thinF_IMG_20150604_

In [23]:
for y, img_name in enumerate(unparasitized_images):
    if img_name.split(".")[1]=="png":
        img=cv2.imread(image_directory+"/unparasitized/"+img_name)
        img=Image.fromarray(img,"RGB")
        img=img.resize((size,size))
        dataset.append(np.array(img))
        label.append(1)

In [24]:
len(dataset)

1000

In [25]:
len(label)

1000

In [26]:
input_shape=(size,size,3)
inp = layers.Input(shape=input_shape)

con1 = layers.Conv2D(32, kernel_size=(3,3),activation = "relu",padding="same")(inp)

max1 = layers.MaxPooling2D(pool_size= (2,2))(con1)

norm1 = layers.BatchNormalization(axis=-1)(max1)

drop1 =layers.Dropout(rate=0.20)(norm1)

In [27]:
con2 = layers.Conv2D(32, kernel_size = (3,3), activation ="relu",padding ="same")(drop1)

max2 = layers.MaxPooling2D(pool_size=(2,2))(con2)

norm2 =layers.BatchNormalization(axis=-1)(max2)

drop2= layers.Dropout(rate = 0.20)(norm2)

In [28]:
flat = layers.Flatten()(drop2)

In [29]:
hidden1= layers.Dense(512,activation="relu")(flat)

norm3 = layers.BatchNormalization(axis=-1)(hidden1)

drop3 = layers.Dropout(rate=0.20)(norm3)

In [30]:
hidden2 = layers.Dense(256,activation="relu")(drop3)

norm4 = layers.BatchNormalization(axis=-1)(hidden2)

drop4 = layers.Dropout(rate = 0.20)(norm4)

In [31]:
out = layers.Dense(2, activation ="sigmoid")(drop4)

In [32]:
model = keras.Model(inputs=inp,outputs=out)

In [33]:
model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 64, 64, 3)]       0         
_________________________________________________________________
conv2d (Conv2D)              (None, 64, 64, 32)        896       
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 32, 32, 32)        0         
_________________________________________________________________
batch_normalization (BatchNo (None, 32, 32, 32)        128       
_________________________________________________________________
dropout (Dropout)            (None, 32, 32, 32)        0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 32, 32, 32)        9248      
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 16, 16, 32)        0     

In [34]:
len(dataset)

1000

In [35]:
len(label)

1000

In [36]:
dataset[0]

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=uint8)

In [37]:
from tensorflow.keras.utils import to_categorical

In [38]:
np.array(label)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [39]:
label_cat = to_categorical(np.array(label))

In [40]:
label_cat

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       ...,
       [0., 1.],
       [0., 1.],
       [0., 1.]], dtype=float32)

In [41]:
from sklearn.model_selection import train_test_split

In [42]:
x_train,x_test,y_train,y_test=train_test_split(dataset,label_cat,test_size=0.20,random_state=0)

In [43]:
len(x_train)

800

In [44]:
len(x_test)

200

In [45]:
model.compile(optimizer="adam",loss="categorical_crossentropy",metrics=["accuracy"])

In [46]:
model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 64, 64, 3)]       0         
_________________________________________________________________
conv2d (Conv2D)              (None, 64, 64, 32)        896       
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 32, 32, 32)        0         
_________________________________________________________________
batch_normalization (BatchNo (None, 32, 32, 32)        128       
_________________________________________________________________
dropout (Dropout)            (None, 32, 32, 32)        0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 32, 32, 32)        9248      
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 16, 16, 32)        0     

In [47]:
x_train

[array([[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        ...,
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]], dtype=uint8),
 array([[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[0, 

In [48]:
np.array(x_train)

array([[[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        ...,

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]],


       [[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0,

In [49]:
model.fit(np.array(x_train),y_train,epochs=25,batch_size=64,verbose=1,shuffle=False)

Epoch 1/25
13/13 [==============================] - 14s 487ms/step - loss: 1.0140 - accuracy: 0.6363
Epoch 2/25
13/13 [==============================] - 7s 529ms/step - loss: 0.4795 - accuracy: 0.7862
Epoch 3/25
13/13 [==============================] - 7s 520ms/step - loss: 0.3187 - accuracy: 0.8750
Epoch 4/25
13/13 [==============================] - 8s 625ms/step - loss: 0.2343 - accuracy: 0.9050
Epoch 5/25
13/13 [==============================] - 7s 493ms/step - loss: 0.1472 - accuracy: 0.9475
Epoch 6/25
13/13 [==============================] - 6s 484ms/step - loss: 0.1426 - accuracy: 0.9438
Epoch 7/25
13/13 [==============================] - 7s 504ms/step - loss: 0.1174 - accuracy: 0.9625
Epoch 8/25
13/13 [==============================] - 6s 481ms/step - loss: 0.1023 - accuracy: 0.9575
Epoch 9/25
13/13 [==============================] - 7s 502ms/step - loss: 0.0755 - accuracy: 0.9787
Epoch 10/25
13/13 [==============================] - 6s 496ms/step - loss: 0.0642 - accuracy: 0.975

In [50]:
model.evaluate(np.array(x_test),y_test)

7/7 [==============================] - 1s 71ms/step - loss: 0.4593 - accuracy: 0.8700


[0.4592961072921753, 0.8700000047683716]

In [51]:
pwd

'C:\\Users\\admin\\Malaria Cell Classification'